SELECT * FROM CUSTOMERS;

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE ADDNEWCUSTOMER(
    P_CUSTOMER_ID IN CUSTOMERS.CUSTOMERID%TYPE,
    P_NAME        IN CUSTOMERS.NAME%TYPE,
    P_DOB         IN CUSTOMERS.DOB%TYPE,
    P_BALANCE     IN CUSTOMERS.BALANCE%TYPE
) AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('INSERTING...');
    DBMS_OUTPUT.PUT_LINE('CUSTOMER_ID : ' || P_CUSTOMER_ID);
    DBMS_OUTPUT.PUT_LINE('NAME        : ' || P_NAME);
    DBMS_OUTPUT.PUT_LINE('DOB         : ' || TO_CHAR(P_DOB, 'YYYY-MM-DD'));
    DBMS_OUTPUT.PUT_LINE('BALANCE     : ' || P_BALANCE);
    
    INSERT INTO CUSTOMERS (CUSTOMERID, NAME, DOB, BALANCE, LASTMODIFIED)
    VALUES (P_CUSTOMER_ID, P_NAME, P_DOB, P_BALANCE, SYSDATE);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Customer added successfully.');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Error: Customer ID ' || P_CUSTOMER_ID || ' already exists.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Customer addition failed: ' || SQLERRM);
END ADDNEWCUSTOMER;
/

EXEC ADDNEWCUSTOMER(3, 'ABHIJIT DAS', TO_DATE('2003-10-02', 'YYYY-MM-DD'), 50000);

SELECT * FROM CUSTOMERS;